# Указываем базовый образ
FROM python:3.10.11

# Устанавливаем рабочую директорию в контейнере
WORKDIR /app

# Копируем файл requirements.txt в рабочую директорию контейнера
COPY requirements.txt .

# Устанавливаем зависимости, указанные в requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Копируем все файлы из текущей директории на хосте в рабочую директорию контейнера
COPY . .

# Экспонируем порт, на котором Streamlit слушает
EXPOSE 8501

# Команда для запуска Streamlit приложения
CMD ["streamlit", "run", "backend_prototype/app.py", "--server.port=8501", "--server.address=0.0.0.0"]
