version: '3'

services:

  streamlit:
    build: 
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://fastapi:8000
    depends_on:
      - fastapi

  fastapi:
    build:
      context: .  
      dockerfile: Dockerfile.fastapi
    ports:
      - "8000:8000"
