FROM python:3.10.11

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем файл зависимостей в контейнер
COPY requirements.txt ./

# Устанавливаем зависимости
RUN pip install --no-cache-dir -r requirements.txt

# Копируем все файлы приложения в контейнер
COPY . .

# Указываем команду для запуска приложения
CMD ["uvicorn", "rag_backend.self_rag_api:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]